import java.util.Properties
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.multiplatform")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("org.jetbrains.compose")
    id("com.github.triplet.play")
}

/**
 * Release signing, kept out of the repository: see keystore.properties.example for the four
 * values and README for how to make the keystore. Absent — which it is on any machine but the
 * one that holds the key — the release build stays unsigned rather than failing, so everything
 * else about it can still be built and checked.
 */
val keystoreProperties = Properties().apply {
    val file = rootProject.file("keystore.properties")
    if (file.exists()) file.inputStream().use { load(it) }
}

/** Whatever git says here, or null where there is no git — a source tarball still builds. */
fun git(vararg args: String): String? = runCatching {
    ProcessBuilder("git", *args).directory(rootDir).start()
        .inputStream.bufferedReader().readText().trim()
}.getOrNull()?.takeIf { it.isNotEmpty() }

/**
 * The build number. CI passes it so both platforms take it from the same run and can never
 * disagree about which build they are; a build off a laptop counts the commits instead.
 *
 * Counting commits rather than keeping a number in a file is what makes a release build off this
 * machine uploadable without bookkeeping: Play rejects a versionCode it has already seen, and the
 * old fallback of 1 meant every local bundle claimed to be the first one. It also has the property
 * a stored counter does not — nothing to forget to bump, nothing to merge, and the same commit
 * always answers the same number.
 *
 * The consequence is worth knowing: a second upload needs a second commit. Rebuilding the same
 * commit gives Play a number it has already taken, which is the honest answer, since it is also
 * the same app.
 *
 * Falls back to 1 only where neither CI nor git can say — a tarball, where nothing is being
 * released anyway.
 */
val buildNumber: String =
    System.getenv("OPENBREATH_BUILD")?.takeIf { it.isNotBlank() }
        ?: git("rev-list", "--count", "HEAD")
        ?: "1"

/**
 * Written into commonMain rather than into a BuildConfig or an Info.plist, because both
 * platforms need it and one generated Kotlin file cannot drift the way two mechanisms would.
 *
 * The sha is what actually answers "which build is this" — a version number says which release
 * was intended, a commit says what the binary was made of. GITHUB_SHA first so a shallow CI
 * checkout still knows, falling back to git, then to "unknown" so a source tarball still builds.
 */
val generateBuildInfo by tasks.registering {
    val dir = layout.buildDirectory.dir("generated/buildinfo/kotlin")
    outputs.dir(dir)
    val version = "1.0.$buildNumber"
    val sha = System.getenv("GITHUB_SHA")?.take(7)
        ?: git("rev-parse", "--short=7", "HEAD")
        ?: "unknown"
    inputs.property("version", version)
    inputs.property("sha", sha)
    doLast {
        val file = dir.get().file("io/github/wlemkens/openbreath/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package io.github.wlemkens.openbreath

            /** Generated by the build — see generateBuildInfo in app/build.gradle.kts. */
            internal const val BUILD_SHA: String = "$sha"
            internal const val BUILD_VERSION: String = "$version"

            """.trimIndent()
        )
    }
}

kotlin {
    // kotlinx-datetime 0.8 hands back the stdlib's kotlin.time.Instant, which Kotlin 2.2 still
    // marks experimental. Opting in once here rather than annotating every file that reads a
    // clock; the type is stable in practice and stops being experimental in 2.3.
    compilerOptions { optIn.add("kotlin.time.ExperimentalTime") }

    androidTarget {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }

    /**
     * The device and the simulator, which are both arm64 but not the same arm64. No iosX64:
     * Compose Multiplatform stopped publishing it at 1.11, so the Intel-Mac simulator is off
     * the table — adding the target back would only fail to resolve. Configuring these costs
     * nothing on Linux; building them needs Xcode, so the link tasks only run on the Mac.
     */
    listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
        target.binaries.framework {
            baseName = "OpenBreath"
            isStatic = true
            // without it the compiler warns that it cannot infer one and falls back to the bundle
            // name, which is what a crash report would then have to be symbolicated against
            binaryOption("bundleId", "io.github.wlemkens.openbreath.shared")
        }
    }

    sourceSets {
        commonMain { kotlin.srcDir(generateBuildInfo) }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            // JetBrains' multiplatform build of androidx.lifecycle, versioned in step with it:
            // 2.10+ still wants compileSdk 37 / AGP 9, so the ceiling that held before the port
            // holds after it. 2.9.6 has LifecycleEventEffect and builds on 36.
            implementation("org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose:2.9.6")
            implementation("androidx.datastore:datastore-preferences:1.2.1")
            implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
            implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.8.0")
        }
        androidMain.dependencies {
            implementation("androidx.activity:activity-compose:1.13.0")
        }
        // The session engine, the stored shape and the cue are checked on every platform that
        // runs them, not just Android. StorageTest especially: a backup written on a phone has to
        // open on an iPhone, so the strings older releases really wrote are now decoded by both
        // compilers rather than one.
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
        // JUnit stays for what is genuinely Android's: the icon generator, the interruption-filter
        // arithmetic, and the reminder scheduling still sitting on java.time.
        val androidUnitTest by getting {
            dependencies { implementation("junit:junit:4.13.2") }
        }
    }
}

/**
 * The generated accessor for commonMain/composeResources — `Res.readBytes("files/…")`.
 *
 * Named explicitly rather than left to the default, which derives a package from the group and
 * module and so changes if either is ever renamed. The two bowls are reached through this on both
 * platforms: they are recordings and not arithmetic, so unlike the bell they cannot simply be
 * computed on each side.
 */
compose.resources {
    packageOfResClass = "io.github.wlemkens.openbreath.media"
    publicResClass = false
}

/**
 * IconGen regenerates the launcher icon and the iOS app icon, and only when asked:
 * `./gradlew :app:testDebugUnitTest -Picons=true`. A Gradle property rather than an environment
 * variable because a test JVM inherits the daemon's environment, not the shell's, so an env var
 * would work or not depending on whether a daemon was already warm.
 */
tasks.withType<Test>().configureEach {
    systemProperty("openbreath.icons", providers.gradleProperty("icons").getOrElse("false"))
}

android {
    namespace = "io.github.wlemkens.openbreath"
    compileSdk = 36

    defaultConfig {
        applicationId = "io.github.wlemkens.openbreath"
        minSdk = 26
        targetSdk = 36
        // CI's run number, or the commit count off a laptop — see buildNumber. Play needs this
        // to increase on every upload, which is the whole reason it is never simply 1
        versionCode = buildNumber.toInt()
        versionName = "1.0.$buildNumber"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    signingConfigs {
        if (keystoreProperties.isNotEmpty()) {
            create("release") {
                storeFile = rootProject.file(keystoreProperties.getProperty("storeFile"))
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.findByName("release")
            isMinifyEnabled = false
        }
    }
}

/**
 * Uploading to Play over the Developer API, so that a closed-testing update is one command
 * instead of a browser and a drag. `./gradlew :app:publishBundle` builds, signs and uploads;
 * README has how to make the service account and what it must be granted. Run the aggregate
 * `publishBundle` and not `publishReleaseBundle` — the per-variant one exists but is registered
 * too late for Gradle to select it by name, so asking for it directly says "task not found".
 *
 * Off unless the credentials are actually here, for the same reason the signing config is: on
 * CI and on any machine but the one holding the key, configuring a publish that cannot happen
 * would fail the build for everyone who only wants to compile. A publish task run without the
 * file says so; nothing else notices it is missing.
 *
 * The track is Play's own name for it, and "alpha" *is* closed testing — the Console calls it
 * "Closed testing" while the API has always called it alpha. A track created by hand carries
 * whatever name it was given, so `-PplayTrack=…` overrides. Getting this wrong is the one
 * mistake that uploads a tester build to the wrong audience, so it is worth reading twice.
 */
val playCredentials = rootProject.file("play-service-account.json")

/**
 * Release notes, written from the commit subjects instead of by hand. The subjects in this
 * repository are already sentences about what changed and who it is for, which is what a release
 * note is; keeping a second hand-written copy of them would drift from the first.
 *
 * `src/main/play` and not `src/androidMain/play`, which is what the source layout would suggest:
 * the plugin reads AGP's own `main` name rather than the KMP one. Verified by letting
 * `bootstrapListing` choose the path — worth remembering, since guessing gets it wrong and the
 * only symptom is notes that silently do not appear.
 *
 * `default.txt` covers every track, so alpha and internal cannot disagree about what a build was.
 *
 * Play truncates at 500 characters, so the newest subjects are taken until the budget runs out.
 * Older ones fall off the bottom rather than being cut mid-word.
 *
 * ponytail: stateless — it says "the most recent changes", not "everything since the last
 * upload", so two releases close together repeat a line. Answering it exactly needs a record of
 * what was last published; tag the release and read the range if the repetition ever grates.
 */
val releaseNotesFile = layout.projectDirectory.file("src/main/play/release-notes/en-US/default.txt")

val generateReleaseNotes by tasks.registering {
    description = "Writes the Play release notes from recent commit subjects."
    outputs.file(releaseNotesFile)
    // the log moves under it with every commit, and the task costs one git call
    outputs.upToDateWhen { false }
    doLast {
        val budget = 500
        val notes = mutableListOf<String>()
        var used = 0
        for (subject in (git("log", "--format=%s", "-40") ?: "").lines().filter(String::isNotBlank)) {
            val line = "- $subject"
            if (used + line.length + 1 > budget) break
            notes += line
            used += line.length + 1
        }
        // a tarball with no git says nothing rather than shipping an empty release note
        val text = notes.joinToString("\n").ifEmpty { "Small fixes and improvements." }
        releaseNotesFile.asFile.apply { parentFile.mkdirs() }.writeText(text + "\n")
        logger.lifecycle("release notes — ${text.length + 1} of $budget characters:\n$text")
    }
}

// The per-variant task is the one that reads the notes, and it is registered too late to be named
// on the command line — so match by name rather than resolving it, and cover the aggregate too.
tasks.matching { it.name == "publishBundle" || it.name == "publishReleaseBundle" }
    .configureEach { dependsOn(generateReleaseNotes) }

play {
    enabled.set(playCredentials.exists())
    serviceAccountCredentials.set(playCredentials)
    track.set(providers.gradleProperty("playTrack").orElse("alpha"))
    // this project ships bundles; without it the publish tasks would look for an APK
    defaultToAppBundles.set(true)
}
